In [20]:
import torch.nn as nn
import torch

In [21]:
x = torch.tensor([[3, 1],[2, 2]],dtype=torch.float)

In [28]:
x

tensor([[3., 1.],
        [2., 2.]])

In [30]:
nn.LayerNorm(x.dim())(x)

tensor([[ 1.0000, -1.0000],
        [ 0.0000,  0.0000]], grad_fn=<NativeLayerNormBackward0>)

In [32]:
x.dim()

2

In [33]:
y = torch.randn((2,2,2,2,2,111))

In [34]:
y.dim()

6

In [37]:
y

tensor([[[[[[ 0.,  0.,  0.,  ...,  0.,  0., -1.],
            [ 0., -2., -1.,  ..., -1.,  0.,  0.]],

           [[ 0., -1.,  1.,  ..., -1., -1., -1.],
            [ 0.,  0.,  0.,  ...,  1., -1.,  1.]]],


          [[[ 0.,  0., -1.,  ...,  1., -1., -2.],
            [-1., -1., -1.,  ...,  1., -1.,  0.]],

           [[-2., -2., -1.,  ..., -1.,  0., -1.],
            [ 2., -1.,  0.,  ...,  1.,  1.,  0.]]]],



         [[[[-1., -1.,  1.,  ..., -1., -3., -1.],
            [ 1., -2., -1.,  ..., -1.,  0., -2.]],

           [[ 2., -1.,  0.,  ...,  0.,  0.,  2.],
            [ 0., -1., -1.,  ...,  0., -2.,  0.]]],


          [[[ 1., -3., -1.,  ..., -2., -1.,  0.],
            [ 1., -1., -1.,  ..., -1.,  0., -1.]],

           [[-1., -1., -1.,  ...,  0., -2., -1.],
            [-2.,  1.,  0.,  ..., -1.,  0., -1.]]]]],




        [[[[[-5.,  0.,  2.,  ..., -1., -2.,  0.],
            [ 2.,  1., -2.,  ...,  0., -1., -2.]],

           [[-1., -1.,  1.,  ..., -3.,  0.,  1.],
            [ 0., 

In [38]:
nn.LayerNorm(111)(y)

tensor([[[[[[ 0.5208,  0.5208,  0.5208,  ...,  0.5208,  0.5208, -0.4590],
            [ 0.4770, -1.7290, -0.6260,  ..., -0.6260,  0.4770,  0.4770]],

           [[ 0.4990, -0.4560,  1.4541,  ..., -0.4560, -0.4560, -0.4560],
            [ 0.4655,  0.4655,  0.4655,  ...,  1.4051, -0.4740,  1.4051]]],


          [[[ 0.5614,  0.5614, -0.4122,  ...,  1.5350, -0.4122, -1.3859],
            [-0.5297, -0.5297, -0.5297,  ...,  1.4303, -0.5297,  0.4503]],

           [[-1.3893, -1.3893, -0.4714,  ..., -0.4714,  0.4466, -0.4714],
            [ 2.1187, -0.7147,  0.2297,  ...,  1.1742,  1.1742,  0.2297]]]],



         [[[[-0.4665, -0.4665,  1.6049,  ..., -0.4665, -2.5379, -0.4665],
            [ 1.3250, -1.4326, -0.5134,  ..., -0.5134,  0.4058, -1.4326]],

           [[ 2.6938, -0.3782,  0.6458,  ...,  0.6458,  0.6458,  2.6938],
            [ 0.6790, -0.3678, -0.3678,  ...,  0.6790, -1.4146,  0.6790]]],


          [[[ 1.4729, -2.5147, -0.5209,  ..., -1.5178, -0.5209,  0.4760],
            [ 1.61

In [39]:
nn.Identity()

Identity()

In [40]:
nn.Identity()(x)

tensor([[3., 1.],
        [2., 2.]])

In [41]:
x

tensor([[3., 1.],
        [2., 2.]])

In [42]:
x.shape

torch.Size([2, 2])

In [46]:
nn.Parameter(x).expand(x.shape[0],-1)

tensor([[3., 1.],
        [2., 2.]], grad_fn=<ExpandBackward0>)

In [48]:
cls_token = nn.Parameter(torch.zeros(1, 1, 178))

In [49]:
cls_token.shape

torch.Size([1, 1, 178])

In [50]:
x = torch.randn((8,1,178))

In [53]:
cls_token = cls_token.expand(x.shape[0],-1,-1)

In [54]:
cls_token.shape

torch.Size([8, 1, 178])